"
This code was auto-generated by Amua (https://github.com/zward/Amua)
Code generated: Mon Dec 30 15:34:09 CST 2019
Model name: DraculaParty
Model type: Decision Tree
Simulation type: Cohort
Created by: szu-yukao
Created: Mon Dec 16 22:49:30 CST 2019
Version created: 0.2.6
Modified by: szu-yukao
Modified: Mon Dec 30 15:33:37 CST 2019
Version modified: null
"

### Define Node Class
setRefClass("Node",
  fields = list(name="character", prob="numeric", 
             costCost="numeric", payoffCost="numeric", expectedCost="numeric", 
             costEff1="numeric", payoffEff1="numeric", expectedEff1="numeric", 
             costEff2="numeric", payoffEff2="numeric", expectedEff2="numeric", 
             children="vector")
)

### Define Run tree
evaluateNode <- function(curNode) {
  # Recursive function to average and roll-back tree
  #
  # Args:
  #   curNode: Current node.  Children will be evaluated recursively.

  numChildren <- length(curNode$children)
  if (numChildren == 0) {
    curNode$expectedCost <- curNode$payoffCost + curNode$costCost
    curNode$expectedEff1 <- curNode$payoffEff1 + curNode$costEff1
    curNode$expectedEff2 <- curNode$payoffEff2 + curNode$costEff2
  } else {  # Evaluate children
    curNode$expectedCost <- curNode$costCost
    curNode$expectedEff1 <- curNode$costEff1
    curNode$expectedEff2 <- curNode$costEff2
    for (i in 1:numChildren) {
      child <- tree[[curNode$children[i]]]  # Get child
      evaluateNode(child)
      curNode$expectedCost <- curNode$expectedCost + (child$prob * child$expectedCost)
      curNode$expectedEff1 <- curNode$expectedEff1 + (child$prob * child$expectedEff1)
      curNode$expectedEff2 <- curNode$expectedEff2 + (child$prob * child$expectedEff2)
    }
  }
}

### Define display results
displayEV <- function(curNode) {
  # Recursive function to display results
  #
  # Args:
  #   curNode: Current node.  Child results will be displayed recursively.
  numChildren <- length(curNode$children)
  if (numChildren > 0) {
    for(i in 1:numChildren) {
      curChild <- tree[[curNode$children[i]]]
      print(paste(curChild$name, curChild$expectedCost, curChild$expectedEff1, curChild$expectedEff2))
      displayEV(curChild)
    }
  }
}


### Define parameters
p_inf_bitten <- 0.5  # Expression: 0.5
p_inf_not_allergic <- 0.4  # Expression: 0.4
p_inf_bitten_UA <- 0.05  # Expression: 0.05
C_hospital <- 500.0  # Expression: 500
C_donothing <- 5.0  # Expression: 5
C_drug <- 10.0  # Expression: 10
C_drug_UA <- 0.5  # Expression: 0.5
p_hospital <- 0.66  # Expression: 0.66
p_bite <- 0.25  # Expression: 0.25
p_not_allerg <- 0.95  # Expression: 0.95
red_blood <- 0.1  # Expression: 0.1

### Create tree
Root <- new("Node", name="Root", children=c(2, 3, 4))
Donothing <- new("Node", name="Donothing", prob=0, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(5, 6))
Universalantibiotics <- new("Node", name="Universalantibiotics", prob=0, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(15, 16))
Targetedantibiotics <- new("Node", name="Targetedantibiotics", prob=0, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(9, 10))
bitten <- new("Node", name="bitten", prob=p_bite, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(7, 8))
notbitten <- new("Node", name="notbitten", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_donothing, payoffEff1=0, payoffEff2=0)
infection <- new("Node", name="infection", prob=p_inf_bitten, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(21, 22))
noinfection <- new("Node", name="noinfection", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_donothing, payoffEff1=0, payoffEff2=0)
bitten1 <- new("Node", name="bitten1", prob=p_bite, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(11, 12))
notbitten1 <- new("Node", name="notbitten1", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_donothing, payoffEff1=0, payoffEff2=0)
notallergic <- new("Node", name="notallergic", prob=p_not_allerg, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(13, 14))
allergic <- new("Node", name="allergic", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_hospital+C_donothing+C_drug, payoffEff1=0, payoffEff2=1)
infection1 <- new("Node", name="infection1", prob=p_inf_not_allergic, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(23, 24))
noinfection1 <- new("Node", name="noinfection1", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_donothing+C_drug, payoffEff1=470, payoffEff2=0)
notallergic1 <- new("Node", name="notallergic1", prob=p_not_allerg, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(17, 18))
allergic1 <- new("Node", name="allergic1", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_hospital+C_donothing+C_drug_UA, payoffEff1=0, payoffEff2=1)
bitten2 <- new("Node", name="bitten2", prob=p_bite, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(19, 20))
notbitten2 <- new("Node", name="notbitten2", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_donothing+C_drug_UA, payoffEff1=0, payoffEff2=0)
infection2 <- new("Node", name="infection2", prob=p_inf_bitten_UA, costCost=0, costEff1=0, costEff2=0, payoffCost=0, payoffEff1=0, payoffEff2=0, children=c(25, 26))
noinfection2 <- new("Node", name="noinfection2", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_donothing+C_drug_UA, payoffEff1=470, payoffEff2=0)
hospitalization <- new("Node", name="hospitalization", prob=p_hospital, costCost=0, costEff1=0, costEff2=0, payoffCost=C_hospital+C_donothing, payoffEff1=470*(1-red_blood), payoffEff2=1)
nohospitalization <- new("Node", name="nohospitalization", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_donothing, payoffEff1=470, payoffEff2=0)
hospitalization1 <- new("Node", name="hospitalization1", prob=p_hospital, costCost=0, costEff1=0, costEff2=0, payoffCost=C_hospital+C_donothing+C_drug, payoffEff1=470*(1-red_blood), payoffEff2=1)
nohospitalization1 <- new("Node", name="nohospitalization1", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_donothing+C_drug, payoffEff1=470, payoffEff2=0)
hospitalization2 <- new("Node", name="hospitalization2", prob=p_hospital, costCost=0, costEff1=0, costEff2=0, payoffCost=C_hospital+C_donothing+C_drug_UA, payoffEff1=470*(1-red_blood), payoffEff2=1)
nohospitalization2 <- new("Node", name="nohospitalization2", prob=-1, costCost=0, costEff1=0, costEff2=0, payoffCost=C_donothing+C_drug_UA, payoffEff1=470, payoffEff2=0)
tree <- c(Root, Donothing, Universalantibiotics, Targetedantibiotics, bitten, notbitten, infection, noinfection, bitten1, notbitten1, notallergic, allergic, infection1, noinfection1, notallergic1, allergic1, bitten2, notbitten2, infection2, noinfection2, hospitalization, nohospitalization, hospitalization1, nohospitalization1, hospitalization2, nohospitalization2)

### Define complementary probs
notbitten$prob <- 1.0 - bitten$prob
noinfection$prob <- 1.0 - infection$prob
notbitten1$prob <- 1.0 - bitten1$prob
allergic$prob <- 1.0 - notallergic$prob
noinfection1$prob <- 1.0 - infection1$prob
allergic1$prob <- 1.0 - notallergic1$prob
notbitten2$prob <- 1.0 - bitten2$prob
noinfection2$prob <- 1.0 - infection2$prob
nohospitalization$prob <- 1.0 - hospitalization$prob
nohospitalization1$prob <- 1.0 - hospitalization1$prob
nohospitalization2$prob <- 1.0 - hospitalization2$prob

### Run tree
evaluateNode(tree[[1]])

### Display output for each strategy
numStrategies <- length(Root$children)
for(i in 1:numStrategies) {
  curNode <- tree[[Root$children[i]]]
  print(paste("Strategy:", curNode$name, curNode$expectedCost, curNode$expectedEff1, curNode$expectedEff2))
	 print("Children...")
	 displayEV(curNode)
}
